// <auto-generated />
using Donately.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Donately.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260428190000_CleanupTestData")]
partial class CleanupTestData
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}

