// <auto-generated />
using Donately.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Donately.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260423195500_FixVerificationWorkflowData")]
partial class FixVerificationWorkflowData
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}

